from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from pymatgen.core import Structure
from pymatgen.electronic_structure.core import Magmom
from pymatgen.io.cif import CifParser, CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from _isotropy_paths import SCRATCH_DIR, configure_environment


configure_environment()


@dataclass
class StandardizationResult:
    standardized_path: Path
    structure: Structure
    method: str
    raw_space_group_number: int
    raw_space_group_symbol: str
    standardized_space_group_number: int
    standardized_space_group_symbol: str
    magnetic_space_group_number_bns: str | None
    magnetic_space_group_symbol_bns: str | None
    basis_vectors: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]] | None
    origin_shift: tuple[float, float, float] | None
    magnetic_symmetry_evaluated: bool


@dataclass
class _FindsymArtifacts:
    generated_cif: Path
    generated_log: Path
    magnetic_symmetry_evaluated: bool


@dataclass
class _FindsymLogSummary:
    basis_vectors: tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]] | None
    origin_shift: tuple[float, float, float] | None
    magnetic_space_group_number_bns: str | None
    magnetic_space_group_symbol_bns: str | None


def _safe_slug(path: Path) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", path.stem)


def _format_triplet(values: tuple[float, float, float] | np.ndarray) -> str:
    return " ".join(f"{float(value):.10f}" for value in values)


def _coerce_moment_vector(moment: object) -> tuple[float, float, float]:
    if isinstance(moment, Magmom):
        vector = np.array(moment.global_moment, dtype=float)
    elif np.isscalar(moment):
        vector = np.array([0.0, 0.0, float(moment)], dtype=float)
    else:
        vector = np.array(moment, dtype=float).reshape(-1)
        if vector.size == 1:
            vector = np.array([0.0, 0.0, float(vector[0])], dtype=float)
    if vector.size != 3:
        raise ValueError(f"Expected a 3-component magnetic moment, got {moment!r}")
    return (float(vector[0]), float(vector[1]), float(vector[2]))


def _extract_magnetic_moments(structure: Structure) -> list[tuple[float, float, float]] | None:
    magmoms = structure.site_properties.get("magmom")
    if magmoms is None:
        return None

    vectors = [_coerce_moment_vector(moment) for moment in magmoms]
    if any(np.linalg.norm(vector) > 1e-12 for vector in vectors):
        return vectors
    return None


def _write_findsym_keyword_input(
    structure: Structure,
    destination: Path,
    tolerance: float,
    magnetic_moments: list[tuple[float, float, float]] | None,
) -> None:
    lattice_matrix = structure.lattice.matrix
    species = [site.specie.symbol for site in structure]

    lines = [
        "!useKeyWords",
        "!title",
        f"Generated by isotropy automation for {destination.stem}",
        "!atomicPositionTolerance",
        f"{tolerance:.10f}",
        "!latticeBasisVectors",
    ]
    lines.extend(_format_triplet(row) for row in lattice_matrix)
    lines.extend([
        "!unitCellBasisVectors",
        "1 0 0",
        "0 1 0",
        "0 0 1",
        "!atomCount",
        str(len(structure)),
        "!atomType",
    ])
    lines.extend(species)
    lines.extend(["!atomPosition"])
    lines.extend(_format_triplet(site.frac_coords) for site in structure)

    occupancies = [float(sum(site.species.values())) for site in structure]
    if any(abs(occ - 1.0) > 1e-12 for occ in occupancies):
        lines.append("!atomOccupation")
        lines.extend(f"{occ:.10f}" for occ in occupancies)

    if magnetic_moments is not None:
        lines.extend(["!magneticMomentTolerance", f"{tolerance:.10f}", "!atomMagneticMoment"])
        lines.extend(_format_triplet(moment) for moment in magnetic_moments)

    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _run_findsym_from_structure(
    structure: Structure,
    workdir: Path,
    tolerance: float,
    magnetic_moments: list[tuple[float, float, float]] | None,
    slug: str,
) -> _FindsymArtifacts | None:
    temp_input = workdir / f"{slug}_findsym.in"
    generated_cif = workdir / "findsym.cif"
    generated_log = workdir / "findsym.log"

    for artifact in (temp_input, generated_cif, generated_log):
        if artifact.exists():
            artifact.unlink()

    _write_findsym_keyword_input(structure, temp_input, tolerance, magnetic_moments)

    subprocess.run(
        ["findsym", temp_input.name],
        capture_output=True,
        text=True,
        cwd=workdir,
        check=False,
    )

    if generated_cif.exists() and generated_log.exists():
        return _FindsymArtifacts(
            generated_cif=generated_cif,
            generated_log=generated_log,
            magnetic_symmetry_evaluated=magnetic_moments is not None,
        )
    return None


def _run_findsym_from_cif(source_cif: Path, workdir: Path, tolerance: float) -> _FindsymArtifacts | None:
    temp_input = workdir / f"{_safe_slug(source_cif)}_findsym.in"
    generated_cif = workdir / "findsym.cif"
    generated_log = workdir / "findsym.log"

    for artifact in (temp_input, generated_cif, generated_log):
        if artifact.exists():
            artifact.unlink()

    local_source = workdir / source_cif.name
    shutil.copyfile(source_cif, local_source)

    with temp_input.open("w", encoding="utf-8") as handle:
        subprocess.run(
            ["findsym_cifinput", local_source.name],
            stdout=handle,
            stderr=subprocess.PIPE,
            text=True,
            cwd=workdir,
            check=False,
        )

    subprocess.run(
        ["findsym", temp_input.name],
        input=f"\n{tolerance}\n",
        capture_output=True,
        text=True,
        cwd=workdir,
        check=False,
    )

    if generated_cif.exists() and generated_log.exists():
        return _FindsymArtifacts(
            generated_cif=generated_cif,
            generated_log=generated_log,
            magnetic_symmetry_evaluated=False,
        )
    return None


def _parse_quoted_cif_value(cif_text: str, tag: str) -> str | None:
    match = re.search(rf"^{re.escape(tag)}\s+(?:\"([^\"]+)\"|'([^']+)'|(\S+))", cif_text, re.MULTILINE)
    if not match:
        return None
    return next(group for group in match.groups() if group is not None)


def _parse_findsym_log(log_path: Path, generated_cif: Path) -> _FindsymLogSummary:
    log_text = log_path.read_text(encoding="utf-8")
    cif_text = generated_cif.read_text(encoding="utf-8") if generated_cif.exists() else ""

    origin_match = re.search(r"Origin at\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)", log_text)
    origin_shift = None
    if origin_match:
        origin_shift = tuple(float(origin_match.group(i)) for i in range(1, 4))

    basis_match = re.search(
        r"Vectors a,b,c:\s*\n\s*([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)\s*\n"
        r"\s*([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)\s*\n"
        r"\s*([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)",
        log_text,
    )
    basis_vectors = None
    if basis_match:
        values = [float(basis_match.group(i)) for i in range(1, 10)]
        basis_vectors = (
            (values[0], values[1], values[2]),
            (values[3], values[4], values[5]),
            (values[6], values[7], values[8]),
        )

    magnetic_space_group_number_bns = _parse_quoted_cif_value(cif_text, "_space_group_magn.number_BNS")
    magnetic_space_group_symbol_bns = _parse_quoted_cif_value(cif_text, "_space_group_magn.name_BNS")

    return _FindsymLogSummary(
        basis_vectors=basis_vectors,
        origin_shift=origin_shift,
        magnetic_space_group_number_bns=magnetic_space_group_number_bns,
        magnetic_space_group_symbol_bns=magnetic_space_group_symbol_bns,
    )


def standardize_cif_with_fallback(
    source_cif: Path,
    output_cif: Path,
    *,
    symprec: float = 1e-3,
    findsym_tolerance: float = 1e-3,
    evaluate_magnetic: bool | None = None,
) -> StandardizationResult:
    raw_structure = CifParser(str(source_cif)).parse_structures(primitive=False)[0]
    raw_analyzer = SpacegroupAnalyzer(raw_structure, symprec=symprec)

    magnetic_moments = _extract_magnetic_moments(raw_structure)
    if evaluate_magnetic is False:
        magnetic_moments = None
    magnetic_requested = magnetic_moments is not None if evaluate_magnetic is None else (evaluate_magnetic and magnetic_moments is not None)

    findsym_workspace_root = SCRATCH_DIR / "findsym_standardize"
    findsym_workspace_root.mkdir(parents=True, exist_ok=True)
    findsym_workspace = Path(tempfile.mkdtemp(prefix=f"{_safe_slug(source_cif)}_", dir=findsym_workspace_root))

    generated = _run_findsym_from_structure(
        raw_structure,
        findsym_workspace,
        findsym_tolerance,
        magnetic_moments if magnetic_requested else None,
        _safe_slug(source_cif),
    )

    if generated is None:
        generated = _run_findsym_from_cif(source_cif, findsym_workspace, findsym_tolerance)

    standardized_structure: Structure
    method: str
    log_summary = _FindsymLogSummary(None, None, None, None)
    magnetic_symmetry_evaluated = False
    if generated is not None:
        standardized_structure = CifParser(str(generated.generated_cif)).parse_structures(primitive=False)[0]
        method = "findsym"
        magnetic_symmetry_evaluated = generated.magnetic_symmetry_evaluated
        log_summary = _parse_findsym_log(generated.generated_log, generated.generated_cif)
        shutil.copyfile(generated.generated_cif, output_cif)
    else:
        standardized_structure = raw_analyzer.get_conventional_standard_structure()
        CifWriter(standardized_structure).write_file(output_cif)
        method = "pymatgen_conventional_standard"

    analyzer = SpacegroupAnalyzer(standardized_structure, symprec=symprec)
    return StandardizationResult(
        standardized_path=output_cif,
        structure=standardized_structure,
        method=method,
        raw_space_group_number=raw_analyzer.get_space_group_number(),
        raw_space_group_symbol=raw_analyzer.get_space_group_symbol(),
        standardized_space_group_number=analyzer.get_space_group_number(),
        standardized_space_group_symbol=analyzer.get_space_group_symbol(),
        magnetic_space_group_number_bns=log_summary.magnetic_space_group_number_bns,
        magnetic_space_group_symbol_bns=log_summary.magnetic_space_group_symbol_bns,
        basis_vectors=log_summary.basis_vectors,
        origin_shift=log_summary.origin_shift,
        magnetic_symmetry_evaluated=magnetic_symmetry_evaluated,
    )
